# Exported from Render on 2026-04-07T17:02:50Z
version: "1"
services:
- type: web
  name: BE_bookstore
  runtime: node
  repo: https://github.com/Duyday2k5/BE_bookstore
  plan: free
  envVars:
  - key: MONGO_DB_URL
    sync: false
  region: oregon
  buildCommand: npm install; npm run build
  startCommand: npm start
  autoDeployTrigger: commit
