# Exported from Render on 2026-04-07T17:02:50Z
version: "1"
services:
- type: web
  name: BE_bookstore
  runtime: node
  repo: https://github.com/Duyday2k5/BE_bookstore
  plan: free
  envVars:
  - key: MONGO_DB_URL
    value: mongodb+srv://nhatduy25:Nnd27092005.@duyday25.pruwivz.mongodb.net/bookstore?retryWrites=true&w=majority&appName=Duyday25
  - key: NODE_ENV
    value: production
  - key: JWT_ACCESS_SECRET
    value: JUSTARANDOMSTRINGACCESS
  - key: JWT_ACCESS_EXPIRE_IN
    value: 10h
  - key: JWT_REFRESH_SECRET
    value: JUSTARANDOMSTRINGREFRESH
  - key: JWT_REFRESH_EXPIRE_IN
    value: 1d
  region: oregon
  buildCommand: npm install --legacy-peer-deps && npm run build
  startCommand: npm start
  autoDeployTrigger: commit
